# Generated by Django 5.1.3 on 2024-12-30 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_reviewratings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewratings',
            options={'verbose_name': 'ReviewRating', 'verbose_name_plural': 'ReviewRatings'},
        ),
    ]
