# Generated by Django 5.1.3 on 2024-12-31 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
        ('store', '0004_alter_reviewratings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewratings',
            name='user_profile',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
            preserve_default=False,
        ),
    ]
