# Generated by Django 5.1.3 on 2024-12-31 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
        ('store', '0005_reviewratings_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewratings',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
