# Generated by Django 5.1.3 on 2024-12-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderproduct'),
        ('store', '0002_productvariation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product_variation',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product_variations',
            field=models.ManyToManyField(blank=True, to='store.productvariation'),
        ),
    ]
